# Generated by Django 4.2.10 on 2025-03-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth_mate_app', '0005_course_created_at_course_is_active_course_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/assets/images/defaultuser.jpg', upload_to='static/profile_images/'),
        ),
    ]
