# Generated by Django 4.2.10 on 2025-03-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth_mate_app', '0007_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cover_pic',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/assets/images/default_profile.png', upload_to='static/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15, default=''),
        ),
    ]
