# Generated by Django 4.2.10 on 2025-03-30 07:48

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('growth_mate_app', '0011_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
