# Generated by Django 4.2.10 on 2025-03-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth_mate_app', '0013_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='email_address',
        ),
    ]
